FROM openshift/origin-release:golang-1.18 as builder

WORKDIR /go/src/github.com/open-cluster-management/hibernate-cronjob
COPY . .

RUN make -f Makefile compile

FROM registry.access.redhat.com/ubi9/ubi-minimal:latest

COPY --from=builder /go/src/github.com/open-cluster-management/hibernate-cronjob/action .

USER 1001